### ISSUE TITLE
[Nested ESXi hosts] Set vlan on default network adapter

### ISSUE THREAD

**Issue by PetterBomban** [lamw/vghetto-scripts#34]
Hi.

I was just wondering if it is possible to set the vlan id on the default network adapter with your nested ESXi hosts?

For example, `$ovfconfig.common.guestinfo.hostname.value = "MyHostName"` 

Is it possible to add `$ovfconfig.common.guestinfo.vlanid.value = 300`?

I'd appreciate any help.

\- Petter

**Comment by lamw** [comment]
@PetterBomban Yes, the key is **vlan** and you can always use Get-OvfConfiguration cmdlet to inspect the options or use OVFTool binary to inspect :)

**Comment by PetterBomban** [comment]
Hi, and thanks for responding.

I can't find the vlan key in any of the properties. The .ova-file I have was downloaded from your website a couple of months ago, and is called "Nested_ESXi6.x_Appliance_Template_v5.ova".

Here's a screenshot of what I got out of Get-OvfConfiguration:

![image](https://i.imgur.com/o5zlHV7.png)

I have also read through the ovf-file, and I haven't found anything vlan related.

Just for clarity, I need to have the vlan set before the host boots, like I can do with the ip address and so on. (With your customized images)

**Comment by lamw** [comment]
This is only available in new Nested ESXi Images (6.5d / 6.0u3)

**Comment by PetterBomban** [comment]
Thanks, you're saving me from some headache right now :)
