### ISSUE TITLE
ESXiDisableProtocolConfiguration.ps1 -VMHost

### ISSUE THREAD

**Issue by meoso** [lamw/vghetto-scripts#35]
`Get-ESXiDPC` doesn't accept the `-VMHost` parameter even though the code implies it does.
Can you implement `-VMHost` for `Set-ESXiDPC` also?

**Comment by lamw** [comment]
That was actually left over code, it expects a vSphere Cluster as input. I've cleaned out the entry. 

You can already see how it retrieves an ESXi host from a Cluster, so you're more than welcome to adjust it to fit your needs but most customers are running this inside of a Cluster, so I've optimized the code for that use.
